FROM node:14-alpine

WORKDIR /usr/src/app

RUN apk update
RUN apk add --no-cache netcat-openbsd
RUN npm install
RUN npm install mysql --save
# RUN npm install pm2 -g

COPY node/alpine-init.sh .
RUN chmod +x alpine-init.sh

EXPOSE 3000
CMD [ "sh", "alpine-init.sh" ]