# Define a imagem base
FROM node:15

# Define o diretório de trabalho da aplicação dentro do container
WORKDIR /usr/src/app

RUN npm install

RUN npm install mysql --save

RUN npm pm2 -g

RUN chmod 777 init.sh

EXPOSE 3000

# ENTRYPOINT [ "./init.sh" ]